import os, sys, stat
tools = os.system('wget https://raw.githubusercontent.com/cqsimple/tech/main/Tools.py')
initial = os.system('wget https://raw.githubusercontent.com/cqsimple/tech/main/initial.py')
update = os.system('wget https://raw.githubusercontent.com/cqsimple/tech/main/update.py')
os.chmod("Tools.py", stat.S_IWOTH)
os.chmod("initial.py", stat.S_IWOTH)
os.chmod("update.py", stat.S_IWOTH)
f = open('.bash_profile', 'a')
f.write("python initial.py")
f.close()
